# In real we can't launch the Pod directly, we always launch the pod using deployment

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeploy
    labels:
      app: web
spec:
    replicas: 4
    minReadySeconds: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 2
    selector:
      matchLabels:
        app: web

    template:
      metadata:
        name: kubesv
        labels:
          app: web
      spec:
        containers:
          - name: mycont
            image: vimal13/apache-webserver-php
